

-- 직원정보 

SELECT * FROM org_employee 
WHERE emp_id = 'M210755610'

SELECT * FROM org_person; 
SELECT * FROM org_my_job; 



SELECT A.EMP_ID,A.OFC_ID, A.DEPT_ID, A.CMP_ID 
      ,B.USER_NAME, B.CMP_EMAIL, B.RETIRE_DATE , B.ECNY_DATE
      ,C.PSN_ID, C.CELL_PHONE , C.PROFILE_IMG , C.BIRTHDATE
      ,D.POS_ID, D.POS_NAME 
      ,E.OFC_NAME 
      ,F.DEPT_NAME 
FROM ORG_MY_JOB A 
INNER JOIN ORG_EMPLOYEE B ON A.EMP_ID = B.EMP_ID 
INNER JOIN ORG_PERSON C ON B.PSN_ID = C.PSN_ID
INNER JOIN ORG_POSITION D ON B.POS_ID = D.POS_ID 
INNER JOIN ORG_OFFICE E ON E.OFC_ID = A.OFC_ID 
INNER JOIN ORG_DEPARTMENT F ON F.DEPT_ID = A.DEPT_ID 
WHERE A.emp_id = 'M651491304'
AND A.BASS_DEPT_YN = 'Y'

